#!/bin/bash

if [ -z "${UPSTREAM_REPO}" ]; then
    echo "UPSTREAM_REPO var is not set or is empty"
    exit 1
fi

if [ -d "tgvc" ]; then
    rm -rf tgvc
    echo "Removed older tgvc directory"
fi

export PIP_ROOT_USER_ACTION=ignore

git clone -q --depth=1 "${UPSTREAM_REPO}"
cd tgvc

pip -q install --no-cache-dir -r req*.txt

python3 -m tgvc & python3 web.py
